spring:
  application:
    name: restaurantreservationpj

  web:
    resources:
      add-mappings: false

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true

  datasource:
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservationpj?characterEncoding=UTF-8

  h2:
    console:
      enabled: true
      path: /h2-console

  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: trace