spring:
  application:
    name: restaurantreservationpj

  web:
    resources:
      add-mappings: false

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true

  datasource:
    username: ${MYSQL_USER_NAME} # 환경 변수
    password: ${MYSQL_PASSWORD} # 환경 변수
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservationpj?characterEncoding=UTF-8

  data:
    redis:
      port: 6379
      host: localhost

  cache:
    type: redis

  jwt:
    secret: ${JWT_SECRET} # 환경 변수

logging:
  level:
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: trace